### ISSUE TITLE
Automatic per user directories?

### ISSUE THREAD

**Issue by vorpalhex** [9001/copyparty#62] opened 2023-11-19 20:31 UTC
I'm not sure if this is already possible or if this is effectively a feature request. 

I have my users managed via the proxy. I'd like each user to get a directory that they'd have broad permissions to. Eg, for the user `sue`, I'd like them to have `/mnt/files/sue/` (and `bob` would get `/mnt/files/bob/`). Ideally in this config this would be a single config entry with a placeholder, something like:

```
[/user]
  /mnt/files/{$USER}/
```

(it's ok if it needs to be a unique directory per user too, eg /user/${USER} in the above example)

## Why

The problem this solves for me is that I have multiple ways for my users to already get at their files (syncthing, ssh, etc) but I'd like users to have a really powerful web interface (copyparty) that is just a lot more convenient for a bunch of my users. I don't want it to be the case that I have to manually update the config for each user. I'd like them to just be able to oauth in and go.

**Comment by 9001** [comment] 2023-11-19 21:29
Hey! This sounds interesting, but there's a few things I'm not quite following -- primarily the part about handling authentication through a proxy.

* I might be jumping to conclusions here, but it sounds like you're not using copyparty's account system at all -- is that right?
* And since authentication is handled by the proxy, I'm also wondering how copyparty would know the identity of requests -- like, how does the proxy convey the username to copyparty?
* Also, out of curiosity, what proxy is this? :-)

**Comment by vorpalhex** [comment] 2023-11-19 21:46
It's traefik + authentik in a reverse proxy auth config (once setup it's really beautifully easy, highly recommend, very docker friendly). 

Yeah, I was initially planning to just setup authentik's basicauth faking. I can't tell if it's sufficient to just do this for the username or if I need to map passwords too. 

I was assembling details for possibly two more supportive feature requests - reverse proxy header auth (given some configurable header like 'X-authentik-username', treat all requests as coming from that username) and group permissions (respect some configurable header like 'X-authentik-groups' and allow assigning permissions to groups instead of users). 

The reason I like the proxy/header based auth flow is because it removes most of the logic from the applications and offers this really nice generic interface where you get very powerful auth/permission patterns without having a bunch of supportive code. Typically the downside of this flow is that you can totally screw it up and leave yourself with horrible security woes (so it should be like disabled by default and other sensible defaults to avoid footguns).

**Comment by 9001** [comment] 2023-11-19 22:01
> configurable header like 'X-authentik-username', treat all requests as coming from that username

sounds dope :+1:

> configurable header like 'X-authentik-groups' and allow assigning permissions to groups instead of users

technically, this would need to be mapped to copyparty's permission flags at some point, so maybe one of the following options:
* you define the groups in copyparty's config file, and assign permissions to groups in there
* or, instead of the proxy sending a group name, the proxy would pass over the copyparty permission flags to assign to the user

I suppose the first option would be better, since then you wouldn't have to consider anything about copyparty's permission system on the proxy side, but it does mean having to drop by the config files once in a while.

> Typically the downside of this flow is that you can totally screw it up and leave yourself with horrible security woes

absolutely! they'll be two different global options where you specify the header name to expect, and specifying a value there also enables the feature.

----

so all in all, this means that users would be generated mostly on-the-fly, so it might be a bit of work to make that possible. I'm kinda stretched on time until xmas but I'll pick this up around then :+1: 

thanks for the idea!

**Comment by vorpalhex** [comment] 2023-11-19 23:07
> I suppose the first option would be better, since then you wouldn't have to consider anything about copyparty's permission system on the proxy side, but it does mean having to drop by the config files once in a while.

I agree. It makes sense to define groups ahead of time, and it's not difficult to setup your main groups and then you can assign them however (by hand, via Discord role mapping to group name, whatever). 

> I'm kinda stretched on time until xmas but I'll pick this up around then 👍

I appreciate it! I will try to swing by and drop off a minimal docker-compose environment with a reverse proxy auth setup (probably authelia based, since it just uses a static config file). Should also be useful for docs.

Thanks for the wonderful software! Copyparty is easily one of my favorite pieces of software and solves a whole host of issues for me!

**Comment by vorpalhex** [comment] 2024-01-02 03:14
Here's a prebuilt example from the Authelia docs with Authelia setup in an auth proxy config, using authelia/authelia as the creds. https://github.com/authelia/authelia/tree/master/examples/compose/lite

**Comment by 9001** [comment] 2024-01-31 05:39
While I'm still working on the remaining features, I think it's ready for some testing at this point -- I've pushed some builds just in case anyone would like to start playing with it, or perhaps try to put together some example configs or docker setups (that would be awesome 👌 )

the sfx is here: https://ocv.me/copyparty-idp.py
grab it from dockerhub: `docker pull copyparty/ac:idp`
alternatively, `podman pull docker.io/copyparty/ac:idp`

currently, it will forget all users and volumes between each restart -- there is plans to have it remember volumes, but probably not users (since that could be dangerous)

and one of the pending features is some sanity checks on startup, in particular to detect the following misconfiguration:

say you define the dynamic volumes `/users/${u}/` for public files, and `/users/${u}/private/` for private files. During a restart, copyparty will forget all users (and possibly volumes, in case of a hard crash). If the `/users` folder is readable by anyone, then unintended users can now access the private volumes, since copyparty doesn't know about those until each user makes themselves known by sending an http request.

so it is strongly recommended to keep all dynamic volumes inside a location where nobody has read-access; for example if `/users` is a volume with no permissions at all, like at the bottom of https://github.com/9001/copyparty/blob/hovudstraum/docs/examples/docker/idp/copyparty.conf

let me know if you hit any unexpected behavior, or just have some questions :>

**Comment by vorpalhex** [comment] 2024-02-06 02:27
Yay! 

Tested and it's working fully for users to login and access statically defined dirs. 

Groups is still funky. It works with predefined group names + predefined group members + idp users, but not able to assign a predefined group name to an idp user via the idp group header. 

I will need to do a bit more testing around dynamic user directories.

**Comment by 9001** [comment] 2024-02-06 11:12
Awesome! thanks for testing :>

Regarding the group issue -- currently it assumes that all requests will have a username provided, since it needs a username to attach the permissions to (in this case, a username to add into the group). Could that be the issue you're hitting?

I guess this could be fixed by autogenerating a username if only the groupname is provided, maybe just the groupname combined with a base64 of the user's IP... I'll fix that in the next build tonight 👍

**Comment by vorpalhex** [comment] 2024-02-06 14:30
Hm, so for testing groups I made two new groups, "admin" and "household". Admin has defined members in the base.conf, and household does not. 

Then I created a test user in the auth proxy that belongs to household and admin. 

It correctly sees the admin assigned folder, but not household. 

Let me grab a request and a config to share tonight.

**Comment by 9001** [comment] 2024-02-06 15:09
curious! in case it makes things easier, you can have copyparty print the idp headers it's getting with `--ihead=x-idp-user --ihead=x-idp-group` :>

**Comment by vorpalhex** [comment] 2024-02-08 03:10
`reinitializing due to new user from IdP: [kyros:authentik Admins|admins|household]`

```
[global]
    ansi

    idp-h-usr: x-authentik-username
    idp-h-grp: x-authentik-groups

[groups]
    admin: kyros
    household: kyros spasticninja
    copyparty:

[/media]
    /mnt/Media
    accs:
        r: *

[/public]
    /mnt/Public
    accs:
        rwmda: @copyparty
```
 
 `X-Authentik-Groups: authentik Admins|admins|household|copyparty` according to `whoami`.
 
  I swapped that Public mount to @household instead and it still doesn't populate.

**Comment by 9001** [comment] 2024-02-08 20:36
ohh RIGHT, a user can be in multiple groups... that's not something I considered heh

I've uploaded a new build of the `copyparty/ac:idp` container and [the sfx](https://ocv.me/copyparty-idp.py), should work better now :+1: 

the character that is used to separate multiple groupnames in the header can now be adjusted on the copyparty side using `--idp-h-sep`, it defaults to any of `|:;+,`

and in the end I didn't make it possible to skip providing a username in requests (and only do a groupname instead) since I can't reall think of any usecases for that, so let me know if that would be useful!

**Comment by vorpalhex** [comment] 2024-02-10 04:44
It works!

> the character that is used to separate multiple groupnames in the header can now be adjusted on the copyparty side using --idp-h-sep, it defaults to any of |:;+,

Thank you. I saw what Authentik was spitting out and I don't know why they thought a pipe was the right character when everyone else uses commas. 

> and in the end I didn't make it possible to skip providing a username in requests (and only do a groupname instead) since I can't reall think of any usecases for that, so let me know if that would be useful!

I also can't think of any usecases for this. 

Thanks again for this feature! It's definitely going to wow my users.

**Comment by 9001** [comment] 2024-02-27 02:02
Quick update; I've been trying to put together a docker-compose example, both for testing and for reference when somebody wants to use this feature, to somewhat limited success...

Should say, part of the reason there's little progress here is a lack of motivation on my end, since this feature won't be useful for myself or any of my friends' instances, and I also doubt I'm the right guy to make decent docker examples / connect everything together... Hopefully someone more familiar and enthusiastic about authentik / traefik / this kind of stuff will be able to do something about that last part though 🤞

Right now, there's an example config based on [authelia+traefik](https://github.com/9001/copyparty/tree/idp/docs/examples/docker/idp-authelia-traefik), which at least powers up and does something (yay). This is using the config syntax changes that will be introduced in the next stable version, so the compose.yml is currently versionlocked to `authelia:v4.38.0-beta3`.

While I was trying to get that to work, I had a go at [authentik+traefik](https://github.com/9001/copyparty/tree/idp/docs/examples/docker/idp-authentik-traefik) as well, but I didn't get very far since I'm not immediately seeing how you're supposed to connect everything together, and the effort kinda fizzled out when I managed to get authelia running. But I'm really curious if this would have better performance than authelia (ref. [the readme](https://github.com/9001/copyparty/tree/idp/docs/examples/docker/idp-authelia-traefik#performance))

some things to look at / deal with before merging this;
* need to determine how secure our examples are, and what warnings / advice to add for anyone considering to use this stuff (important!)
* would be nice to keep track of what we based our examples on, especially if they're "official" ones, so people can base their setups on a more recent upstream example and port our changes to the new ones
* some notes in the READMEs on what you should do to get started, and what should be done to secure it properly
* include some related links to any offsite tutorials / references that we'd recommend looking at

(I know there's some irony here, since a lot of this is also missing for copyparty itself hehe)

Anyways, I'm still hoping we can solve #69 completely on the docker side of things, even considering https://github.com/9001/copyparty/issues/69#issuecomment-1871376421 I'm thinking we could have authentik/authelia allow users to access copyparty even without a valid authentication, maybe by automatically giving them a guest account, or just not providing any auth-headers at all, if that is possible. Alternatively, it would also be fine to hook up the same copyparty instance to traefik under two different routes, so it'd be available both through authentik and also directly, maybe on a separate subdomain if necessary... though I'm not sure where to start looking for any of this really. But this would just be a bonus; can focus on a more basic example and leave that for later :>

**Comment by vorpalhex** [comment] 2024-03-02 21:53
The performance issue definitely appears to be an issue with Authelia, likely caching isn't configured quite right (could be in redis..)

Authentik is rough because it's very GUI driven for configuration _and_ is really complex. The upside is that all that complexity makes it so you can use a plex server or a discord guild as your authentication source (eg if this person has a discord account, and that account is on my server, give them access. If they also have role @admin then assign them the group `admin`). But minimum requirements here are traefik (or other reverse-proxy) + authentik + authentik worker + redis + postgres, which is a lot.

Security wise, I think it's fair to just provide a simple example that isn't secure (with the right warning), but if we wanted to make it secure we'd:
+ Add in a redis password to limit attacker lateral movement in the system
+ Move redis to a private network shared with just authelia
+ Pin to image hashes (or go all in on updates and add `watchtower`)
+ Drop bridge networking for just exposing traefik's public ports
+ Configure docker for non-root access to docker socket and then move traefik to [use non-root perms](https://docs.docker.com/engine/security/rootless/)
+ Drop the default password we specify and instead force users to either generate their own or provide a helper script (I realize this default password is also something authelia does)

I dropped a comment in #69 but I think the share links just need to have a configurable path? Not sure how this feature currently works in copyparty itself to be honest. But yes, paths can be exempted from the auth proxy flow.

**Comment by 9001** [comment] 2024-03-13 23:16
Alright, think this is *finally* wrapping up! The branch has been merged, and I'm aiming to release around sunday 24th.

There's a new build of the `copyparty/ac:idp` container and [the sfx](https://ocv.me/copyparty-idp.py) which should be really close to v1.11.0 unless something shows up. So please let me know if you hit any issues :>

Changes since the last build:
* The whitelisting procedure to trust `x-forwarded-for` now also applies to (and is also required for) the idp headers. This is done using the `xff-src` config option; see [here](https://github.com/9001/copyparty/blob/hovudstraum/docs/examples/docker/idp/copyparty.conf), [here](https://github.com/9001/copyparty/blob/hovudstraum/docs/examples/docker/idp-authelia-traefik/cpp/copyparty.conf) and [here](https://github.com/9001/copyparty/blob/hovudstraum/docs/idp.md) for slightly different examples/explanations
* New optional security feature, `idp-h-key` lets you specify a header-name to expect in all requests -- if this header is not present, all the other IdP headers (username/group) will be ignored, assuming the request is malicious and somehow managed to avoid passing through the authenticator middleware, possibly better explained in the example configs linked above
* The login/logout UI is hidden if the request contains IdP headers
* Added a big warning if unsafe configurations are detected, which could lead to accidentally sharing secret files
* Lots of other fixes unrelated to IdP :-)

The idea to remember IdP volumes (per-user volumes) was abandoned, because things were getting too tricky to reason about. As a result, after a server restart, such volumes will be entirely inaccessible until the associated user sends a request to resuscitate it

> Security wise, I think it's fair to just provide a simple example that isn't secure (with the right warning), but if we wanted to make it secure we'd: [...]

Thanks! Added them to the readme :+1: 

> I dropped a comment in [...] but I think the share links just need to have a configurable path? Not sure how this feature currently works in copyparty itself to be honest. But yes, paths can be exempted from the auth proxy flow.

Awesome, thanks for confirming -- yeah let's leave it for now, it's hopefully gonna be all config anyways...

**Comment by vorpalhex** [comment] 2024-03-14 02:14
Latest update seems to work great! The `xff-src` specification is a bit odd but functions just fine. I'm used to this looking like CIDR notation (`172.24.0.0/16`) vs `172.24` but it works as expected. 

Oh, and ++ to having an option to disable the check. That's actually really critical because sometimes docker (or kube) will give you funny ip address ranges, so it's really nice to have the option to disable it.

**Comment by 9001** [comment] 2024-03-14 07:25
> The xff-src specification is a bit odd but functions just fine.

yeah I know :sweat_smile: it was for performance reasons, faster to compare a string than to parse the IP, or at least that was the hunch --

> sometimes docker (or kube) will give you funny ip address ranges, so it's really nice to have the option to disable it.

hmm, maybe it'd be a good idea to try a CIDR notation after all... would make it possible to allowlist all LAN IPs with something like `xff-src: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16`

~~rather, what are the odds that somebody will accidentally expose their copyparty port to the internet when running it in docker / kube? maybe it's not something we need to worry about at all?~~

EDIT: should mention it is currently *possible* to do this with `xff-src: 10., 172.18., 172.19., 172.20., 172.21., 172.22., 172.23., 172.24., 172.25., 172.26., 172.27., 172.28., 172.29., 172.30., 172.31., 192.168.` but that's like, super cursed lol

EDIT 2: should be easy to get this performing well with some caching, so I'll make it cidr-based :+1:  and specifying `xff-src: lan` will automatically add all LAN ranges

**Comment by 9001** [comment] 2024-03-14 18:15
new builds up with cidr support (the old syntax is still supported too) :+1: 

and added `xff-src: lan` to all the examples, since that should be safe enough :crossed_fingers:

**Closed as completed** 2024-03-15 21:41 UTC
Labels: enhancement
