### ISSUE TITLE
Got myself banned from my own server because private files showed up in a search

### ISSUE THREAD

**Issue by Gremious** [9001/copyparty#61] opened 2023-11-18 13:34 UTC
I have a 'private' volume with permissions only to myself:
```yaml
accs:
     rwmda: gremious
   flags:
     fk: 8
     fka,
```
(I now notice that fk is useless there but that's what it was)

1. Opened new Firefox private window
2. Searched "a" to test #60
3. See files from said private volumes in the search, but they had no thumbnails
4. Get concerned, click file
5. "thank you for playing"
6. ok

**Comment by 9001** [comment] 2023-11-18 14:13
Hello again o/
And thanks a lot for the report -- this sounds funky so I'd like to get it fixed asap, but I'm having problems reproducing it.
Sorry, but could I bother you to try simplifying your config to something that's safe to share in its entirety, without revealing anything secret-ish?

EDIT: if you're also having issues making it happen again, I'm curious what the rest of your setup is like -- mainly whether you have a reverse-proxy or not + how that is configured, since that might be related somehow (although I think/hope that would not affect anything, or cause something like this...)

**Comment by 9001** [comment] 2023-11-18 17:40
Oh wait, think I might know what happened --

Say you're sharing all of `/mnt/nas`, and copyparty creates its per-volume database for that volume, indexing all files within.

Later on, you decide that `/mnt/nas/foo` should only be visible after logging in, so you create a volume there. Copyparty then creates another per-volume database for that volume, and, as you'd expect, the initial database in `/mnt/nas` will no longer be updated with the files inside the `/mnt/nas/foo` volume. The database in `/mnt/nas` should now also forget all of the files in the `foo` subfolder, but I suspect this part went wrong.

Now, when you do a search (without logging in), you'll be seeing the stale results from the `/mnt/nas` database.

----

if this is what you're encountering, then the problem should go away if you temporarily add the following `[global]` option and restart copyparty: `re-dhash` (optionally, commandline argument `--re-dhash`)

you can remove the option after the first restart with the option enabled; all it does is drop some caches, and this will also delay startup a tiny bit (and won't be necessary once we fix this anyways).

to be clear, this should not have been necessary as it should have happened automatically, so this workaround is just to verify that we have the right idea :+1:

**Comment by 9001** [comment] 2023-11-18 20:49
(closed this since i'm 99% sure this is what's happening, but please let me know if i'm wrong! next version will automatically detect and fix this issue on startup)

**Comment by Gremious** [comment] 2023-11-18 21:34
Sorry to report, but I've re-ran with `re-dhash` on both my version and now the new release, and it did not fix the issue.

Slightly more information: It's not clicking on a file that breaks it even, it's just seeing it in search. I search "a" in a private windows and i see broken private files, and from then on, if i refresh - thank you for playing.

Gimme a min, I'll see if i can provide a nice config.

**Comment by 9001** [comment] 2023-11-18 21:35
interesting! looking forward to figuring out what this is :>

**Comment by Gremious** [comment] 2023-11-18 21:52
~~Does order in config matter - could it be that I mount the `/mnt/nas/foo` and then following that,  `/mnt/nas` with more public visibility? Or, in my config, the more-private `% copyparty.d` folders and then following that - the public-read `/home/gremious/data/user/`~~ update: re-arranging does not matter

I've obscured some names and locations, but this is as full as it gets I think [copyparty.zip](https://github.com/9001/copyparty/files/13401551/copyparty.zip)

Also I do run behind a reverse proxy yes, hit me up if you feel that you need that config

**Comment by 9001** [comment] 2023-11-18 22:35
Hm, noticed there's a few `accs:` entries in the config with `rG: *` -- this will give everyone full read-access, and the `G` is ignored since `r` gives more privileges. There are other entries with just `G: *` which is more what I would expect. Is this intentional? But that wouldn't explain the behavior you're seeing anyways...

And just one more thing that seemed a bit off, which I guess is just from the renaming/obscuring, but will mention it anyways: `[/]` is mapped to `/home/gremious/data/user/` and readable by anyone, which means that everyone also has full read-access to `/home/gremious/data/user/jane_and_me`, even though that is a separate volume (`[/jane_feat_me]`), because the names are different (`feat`/`and`). 

But all that said, I'm unfortunately still not able to reproduce the issue, so maybe it's time to add some debug messages to see what's going on... Are you using the sfx.py, or are you running it in docker? And if so, which docker variant are you using? 

> Does order in config matter?

nah; assuming it works as intended then the order of volumes does not matter -- it should behave the same regardless.

> Also I do run behind a reverse proxy yes, hit me up if you feel that you need that config

since it's so easy to reproduce on your end then that's probably not relevant (phew!)

**Comment by 9001** [comment] 2023-11-18 22:38
oh one more question -- which of these volumes was supposed to contain the file that erroneously appeared in the search results?

**Comment by Gremious** [comment] 2023-11-18 23:01
> I noticed there's a few accs: entries in the config with rG: * -- this will give everyone full read-access, and the G is ignored since r gives more privileges. There are other entries with just G: * which is more what I would expect. Is this intentional? 

Oh, I misunderstood the docs then - the readme saying:
> G (upget): same as g except uploaders get to see their own [filekeys](https://github.com/9001/copyparty#filekeys) (see fk in examples below)

I just kind of assumed that g/G is basically necessary for filekey share-links. I read `rG: *` as "anyone can read files and see their filekeys for sharing links - e.g. anyone can see files and share links to anything here". - I guess that's not right, if you can read a url you can link to it...I guess just `r` enough for that then?

---

> which I guess is just from the renaming/obscuring,

Oosp, yes, those are supposed to have the same names
in practice they are not visible to everyone only when logged in as jane or me

---

> Which files are showing erroniously

it would be files from `/gremious/private/` I can see `/gremious/private/README.md` showing up in the search

---

> Are you using the sfx.py, or are you running it in docker? And if so, which docker variant are you using?

I am running the latest `copyparty-sfx.py`  as a systemd service `ExecStart=/usr/bin/python3 /usr/local/bin/copyparty-sfx.py -c /home/gremious/.config/copyparty/config.conf`. Hit me up with any debug releases you want me to run or log commands or w/e!

**Comment by 9001** [comment] 2023-11-18 23:38
Ehh looks like i'm not awake enough for this after all :sweat_smile:  think i'll have something ready in 16 hours or something :+1:

**Comment by Gremious** [comment] 2023-11-18 23:43
Ok sorry I was a bit in a rush - to elaborate a bit better on my permission shenanigans, the idea is:

private - only `user` can see, simple.

protected - `user` can see entire dir, read/write, share links. Then anyone can read files but, only those from the links, they cannot browse the entire directory. Hence the `rwmda: user` + `G: *` permissions

public - `user` can see entire dir, read/write, share links. Anyone else can read the directory fully and share links.

**Comment by Gremious** [comment] 2023-11-18 23:43
And yeah i'm going to sleep now too ehe, have a good one !

**Comment by 9001** [comment] 2023-11-19 11:51
> I just kind of assumed that g/G is basically necessary for filekey share-links

Oh right, yeah that's kinda confusing -- should reword that a bit :+1: 

----

I think we'll have to take the easy way out this time; I've added a filter to exclude search results which belong to other volumes.

Just gonna cross my fingers that I'll eventually bump into the same issue on my own, so I can debug it properly at home -- it's probably happening several levels deep in the [directory indexer](https://github.com/9001/copyparty/blob/8526ef9368eeffbd5cb70d8f4db15486cb7b7770/copyparty/up2k.py#L1054), at which point the number of absolute, relative, and virtual filepaths to keep track of kinda looks [like this](https://ocv.me/pepe-silva.jpg)...

Give [this version](https://ocv.me/copyparty-sfx.py) a try, hopefully the problem should be gone!

but if that doesn't fix it, try adding the new `srch-dbg` option to `[global]` which should make it even stricter (and WAY slower), and it should crash the search with an error message that explains a bit more.

**Comment by Gremious** [comment] 2023-11-19 12:21
> Give [this version](https://ocv.me/copyparty-sfx.py) a try, hopefully the problem should be gone!

Yep, that works! I guess it'll do for now

Well, if ya ever need any help debugging this, hit me up👍

**Closed as completed** 2023-11-19 12:23 UTC
Labels: bug
